apiVersion: v1.0
kind: Deployment
metadata:
  labels:
    app: exoplanet-catalogue-information
    name: exoplanet-catalogue-information
  spec:
    replicas: 2
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: exoplanet-catalogue-information
          tier: backend
      spec:
        containers:
          - env:
            - name: LOG_LEVEL
              value: info
          image: /exoplanet-catalogue-information:18b79ec
          name: exoplanet-catalogue-information
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /app
              port: 3000
              scheme: HTTP
            intialDelaySeconds: 5
            periodSeconds: 10
            successThreshild: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /app
              port: 3000
              scheme: HTTP
            intialDelaySeconds: 5
            periodSeconds: 10
            successThreshild: 1
            timeoutSeconds: 1
          resources
            requests:
              cpu: 400m
              memory: 256Mi
